import Foundation

/// Well-known pasteboard type identifiers used for privacy filtering.
///
/// These follow the community `org.nspasteboard.*` convention that password
/// managers and other privacy-sensitive apps use to opt out of clipboard history.
public enum PasteboardTypes {
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    /// Any of these on the pasteboard means "do not record this".
    public static let privacySensitive: Set<String> = [concealed, transient, autoGenerated]
}

/// Turns a `PasteboardSnapshot` into a `ClipDraft`, or returns `nil` when the
/// content should not be stored (concealed, transient, or empty).
///
/// Pure, dependency-free logic so it can be unit-tested without a pasteboard.
public struct ClipClassifier: Sendable {

    /// Maximum characters kept in the short `preview` snippet.
    public static let previewLimit = 280

    public init() {}

    public func makeDraft(from snapshot: PasteboardSnapshot) -> ClipDraft? {
        // 1. Never store privacy-sensitive content.
        if snapshot.isConcealed || snapshot.isTransient { return nil }

        let trimmedText = snapshot.plainText?.trimmingCharacters(in: .whitespacesAndNewlines)

        // 2. File references win — e.g. a file copied from Finder.
        if !snapshot.fileURLs.isEmpty {
            return ClipDraft(
                kind: .file,
                text: snapshot.fileURLs.joined(separator: "\n"),
                fileURLs: snapshot.fileURLs,
                sourceAppBundleID: snapshot.sourceAppBundleID,
                sourceAppName: snapshot.sourceAppName
            )
        }

        // 3. Raw image bytes on the pasteboard.
        if let imageData = snapshot.imageData, !imageData.isEmpty {
            let isScreenshot = snapshot.types.contains { $0.lowercased().contains("screencapture") }
            return ClipDraft(
                kind: isScreenshot ? .screenshot : .image,
                imageData: imageData,
                imageFileExtension: snapshot.imageFileExtension ?? "png",
                pixelWidth: snapshot.pixelWidth,
                pixelHeight: snapshot.pixelHeight,
                sourceAppBundleID: snapshot.sourceAppBundleID,
                sourceAppName: snapshot.sourceAppName
            )
        }

        // 4. A URL, either advertised by the pasteboard or detected in the text.
        if let urlString = snapshot.urlString?.trimmingCharacters(in: .whitespacesAndNewlines),
           !urlString.isEmpty {
            return ClipDraft(
                kind: .url,
                text: urlString,
                sourceAppBundleID: snapshot.sourceAppBundleID,
                sourceAppName: snapshot.sourceAppName
            )
        }
        if let text = trimmedText, !text.isEmpty, URLDetection.isWholeStringURL(text) {
            return ClipDraft(
                kind: .url,
                text: text,
                sourceAppBundleID: snapshot.sourceAppBundleID,
                sourceAppName: snapshot.sourceAppName
            )
        }

        // 5. Rich text: styled content with a plain-text fallback.
        if let text = trimmedText, !text.isEmpty,
           (snapshot.rtf != nil || (snapshot.html?.isEmpty == false)) {
            return ClipDraft(
                kind: .richText,
                text: text,
                rtfData: snapshot.rtf,
                htmlText: snapshot.html,
                sourceAppBundleID: snapshot.sourceAppBundleID,
                sourceAppName: snapshot.sourceAppName
            )
        }

        // 6. Plain text.
        if let text = trimmedText, !text.isEmpty {
            return ClipDraft(
                kind: .text,
                text: text,
                sourceAppBundleID: snapshot.sourceAppBundleID,
                sourceAppName: snapshot.sourceAppName
            )
        }

        // Nothing worth keeping.
        return nil
    }
}
